export let data = {
  menu: {},
  pages: {
    home: {
      header: {
        subtitle: "",
        title:
          "Dales una mejor experiencia a tus usuarios, lo atractivo entra por los ojos",
        text: "Donec enim urna, venenatis vitae felis non, tempor sagittis ligula. Fusce lobortis elit leo, ac lacinia orci euismod et. Pellentesque at sem lacus.",
        button: "quiero mi web ahora",
        linkButton: "/",
      },
      services: {
        cards: [
          {
            type: "Web design",
            title: "Diseñamos tu web autoaministrable a medida",
            text: "Totalmente personalizado. Te entregamos tu sitio web en 7 a 10 días hábiles!",
            listing: [
              "Sitio Web Autoadministrable (Panel para agregar y modificar información)",
              "Cambios y Revisiones Ilimitadas",
              "Web Hosting Premium - Gratis Por 1 Año!",
              "5 Secciones (Más secciones con costo adicional)",
              "Cuentas de correo corporativas",
              "Integración con WhatsApp",
              "Diseño Responsive (Se adapta a ordenadores, celulares y tablets)",
              "Dominio Web .com.ar Incluído",
              "Mapa de ubicación",
              "Optimizada para buscadores y redes sociales",
              "Certificado SSL (Seguridad)",
              "Formulario de Contacto",
            ],
            button: "Pedir una cotización",
            linkButton: "/",
          },
          {
            type: "Ecommerce",
            title: "Tu tienda en línea lista para generar ganancias",
            text: "Sin comisiones, autoadministrable, y con todo lo que necesitas para vender.",
            listing: [
              "Tienda Web Autoadministrable (Panel para agregar y modificar productos)",
              "Cambios y Revisiones Ilimitadas",
              "Web Hosting Premium - Gratis Por 1 Año!",
              "4 Secciones (Más secciones con costo adicional)",
              "Cuentas de correo corporativas",
              "Integración con WhatsApp",
              "Métodos de pago (Efectivo - Mercado Pago - Transferencia Bancaria)",
              "Diseño Responsive (Se adapta a ordenadores, celulares y tablets)",
              "Dominio Web .com.ar Incluído",
              "Formulario de contacto",
              "Mapa de ubicación",
              "Optimizada para buscadores y redes sociales",
              "Integración con WhatsApp",
              "Certificado SSL (Seguridad)",
            ],
            button: "Pedir una cotización",
            linkButton: "/",
          },
          // {
          //   type: "Marketing",
          //   title: "Campañas en Meta Ads y Google Ads",
          //   text: "Resultados comprobables y garantizados. Somos expertos en Ads.",
          //   listing: [
          //     "Gestión de estrategia publicitaria",
          //     "Optimización de objetivos y resultados",
          //     "Implementación de pauta personalizada",
          //     "Asesoramiento, gestión y soporte técnico",
          //     "Somos Google y Meta Partners",
          //   ],
          //   button: "Pedir una cotización",
          //   linkButton: "/",
          // },
          {
            type: "Seo",
            title: "Haz que todo el mundo encuentre tu sitio web",
            text: "Resultados comprobables y garantizados. Somos expertos en Ads.",
            listing: [
              "Gestión de estrategia publicitaria",
              "Optimización de objetivos y resultados",
              "Implementación de pauta personalizada",
              "Asesoramiento, gestión y soporte técnico",
              "Somos Google y Meta Partners",
            ],
            button: "Pedir una cotización",
            linkButton: "/",
          },
        ],
      },
    },
  },
}; 